# include: package:pedantic_mono/analysis_options.yaml
include: package:flutter_lints/flutter.yaml
linter:
  rules:
    avoid_classes_with_only_static_members: false
    cascade_invocations: false
    comment_references: false
    constant_identifier_names: true
    one_member_abstracts: false
    prefer_relative_imports: true
    use_build_context_synchronously: false
# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options
analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
  errors:
    invalid_annotation_target: ignore