const Map<String, dynamic> mockNowPlayingResponse = {
  "page": 1,
  "results": [
    {
      "adult": false,
      "backdrop_path": "/iIvQnZyzgx9TkbrOgcXx0p7aLiq.jpg",
      "genre_ids": [27, 53],
      "id": 1008042,
      "original_language": "en",
      "original_title": "Talk to Me",
      "overview": "",
      "popularity": 2019.964,
      "poster_path": "/kdPMUMJzyYAc4roD52qavX0nLIC.jpg",
      "release_date": "2023-07-26",
      "title": "トーク・トゥ・ミー",
      "video": false,
      "vote_average": 7.2,
      "vote_count": 712
    },
    {
      "adult": false,
      "backdrop_path": "/8pjWz2lt29KyVGoq1mXYu6Br7dE.jpg",
      "genre_ids": [28, 878, 27],
      "id": 615656,
      "original_language": "en",
      "original_title": "Meg 2: The Trench",
      "overview": "",
      "popularity": 1672.92,
      "poster_path": "/kVIhaNn8zTDVcMFiwthvjLjCJMt.jpg",
      "release_date": "2023-08-02",
      "title": "MEG ザ・モンスターズ２",
      "video": false,
      "vote_average": 7,
      "vote_count": 1832
    },
    {
      "adult": false,
      "backdrop_path": "/ctMserH8g2SeOAnCw5gFjdQF8mo.jpg",
      "genre_ids": [35, 12, 14],
      "id": 346698,
      "original_language": "en",
      "original_title": "Barbie",
      "overview": "",
      "popularity": 1763.378,
      "poster_path": "/gPKtvmMabSQ1EZINhFtB3DGbCpx.jpg",
      "release_date": "2023-07-19",
      "title": "バービー",
      "video": false,
      "vote_average": 7.3,
      "vote_count": 4800
    },
    {
      "adult": false,
      "backdrop_path": "/53z2fXEKfnNg2uSOPss2unPBGX1.jpg",
      "genre_ids": [27, 9648, 53],
      "id": 968051,
      "original_language": "en",
      "original_title": "The Nun II",
      "overview": "",
      "popularity": 1245.738,
      "poster_path": "/zITEUNN0p6AO9LlQbbSIaAEJ1nC.jpg",
      "release_date": "2023-09-06",
      "title": "死霊館のシスター 呪いの秘密",
      "video": false,
      "vote_average": 6.6,
      "vote_count": 242
    },
    {
      "adult": false,
      "backdrop_path": "/c6Splshb8lb2Q9OvUfhpqXl7uP0.jpg",
      "genre_ids": [28, 53],
      "id": 717930,
      "original_language": "en",
      "original_title": "Kandahar",
      "overview": "",
      "popularity": 1176.457,
      "poster_path": "/lCanGgsqF4xD2WA5NF8PWeT3IXd.jpg",
      "release_date": "2023-05-25",
      "title": "Kandahar",
      "video": false,
      "vote_average": 6.8,
      "vote_count": 510
    },
    {
      "adult": false,
      "backdrop_path": "/H6j5smdpRqP9a8UnhWp6zfl0SC.jpg",
      "genre_ids": [28, 878, 12],
      "id": 565770,
      "original_language": "en",
      "original_title": "Blue Beetle",
      "overview": "",
      "popularity": 1409.947,
      "poster_path": "/vNfL4DYnonltukBrrgMmw94zMYL.jpg",
      "release_date": "2023-08-16",
      "title": "Blue Beetle",
      "video": false,
      "vote_average": 7.1,
      "vote_count": 592
    },
    {
      "adult": false,
      "backdrop_path": "/iiXliCeykkzmJ0Eg9RYJ7F2CWSz.jpg",
      "genre_ids": [28, 9648, 53, 80],
      "id": 762430,
      "original_language": "en",
      "original_title": "Retribution",
      "overview": "",
      "popularity": 983.814,
      "poster_path": "/w3CEN9I7eNfs0fcaL6fxzbFLtdI.jpg",
      "release_date": "2023-08-23",
      "title": "バッド・デイ・ドライブ",
      "video": false,
      "vote_average": 6.6,
      "vote_count": 144
    },
    {
      "adult": false,
      "backdrop_path": "/waBWlJlMpyFb7STkFHfFvJKgwww.jpg",
      "genre_ids": [28, 18],
      "id": 678512,
      "original_language": "en",
      "original_title": "Sound of Freedom",
      "overview": "",
      "popularity": 667.659,
      "poster_path": "/kSf9svfL2WrKeuK8W08xeR5lTn8.jpg",
      "release_date": "2023-07-03",
      "title": "Sound of Freedom",
      "video": false,
      "vote_average": 8,
      "vote_count": 460
    },
    {
      "adult": false,
      "backdrop_path": "/jkKVLzLWjSvTnc84VzeljhSy6j8.jpg",
      "genre_ids": [10749, 18],
      "id": 820525,
      "original_language": "en",
      "original_title": "After Everything",
      "overview": "",
      "popularity": 600.971,
      "poster_path": "/gZLGCibvFY4zmt8sWUZcbBTHRtk.jpg",
      "release_date": "2023-09-13",
      "title": "After Everything",
      "video": false,
      "vote_average": 6.4,
      "vote_count": 27
    },
    {
      "adult": false,
      "backdrop_path": "/w2nFc2Rsm93PDkvjY4LTn17ePO0.jpg",
      "genre_ids": [16, 35, 28],
      "id": 614930,
      "original_language": "en",
      "original_title": "Teenage Mutant Ninja Turtles: Mutant Mayhem",
      "overview": "",
      "popularity": 597.799,
      "poster_path": "/9uVzIlUL258BzVJe2AwY5dqoVXn.jpg",
      "release_date": "2023-07-31",
      "title": "ミュータント・タートルズ：ミュータント・パニック！",
      "video": false,
      "vote_average": 7.4,
      "vote_count": 553
    },
    {
      "adult": false,
      "backdrop_path": "/fm6KqXpk3M2HVveHwCrBSSBaO0V.jpg",
      "genre_ids": [18, 36],
      "id": 872585,
      "original_language": "en",
      "original_title": "Oppenheimer",
      "overview": "",
      "popularity": 427.215,
      "poster_path": "/ptpr0kGAckfQkJeJIt8st5dglvd.jpg",
      "release_date": "2023-07-19",
      "title": "Oppenheimer",
      "video": false,
      "vote_average": 8.3,
      "vote_count": 3632
    },
    {
      "adult": false,
      "backdrop_path": "/7I6VUdPj6tQECNHdviJkUHD2u89.jpg",
      "genre_ids": [28, 53, 80],
      "id": 603692,
      "original_language": "en",
      "original_title": "John Wick: Chapter 4",
      "overview":
          "ジョン・ウィックはバワリー・キングと地下に身を潜め主席連合に復讐する方法を見つけ出す。しかし、彼は自由を手にする前に世界中に強力な同盟を持つ殺し屋と対決しなければならない。そして、それは古い友人を敵に変える力を持つ勢力との新たな敵との戦いをも意味するのである。",
      "popularity": 453.346,
      "poster_path": "/jVE0GT7nDUpJY0T8F3i8ygi6YQa.jpg",
      "release_date": "2023-03-22",
      "title": "ジョン・ウィック：コンセクエンス",
      "video": false,
      "vote_average": 7.8,
      "vote_count": 4547
    },
    {
      "adult": false,
      "backdrop_path": "/1HzL603WOer58xtnrRYdSIL5K04.jpg",
      "genre_ids": [35, 12],
      "id": 912908,
      "original_language": "en",
      "original_title": "Strays",
      "overview": "",
      "popularity": 433.528,
      "poster_path": "/glLgzhRkPv9SWJYnKT2PwFK8k6B.jpg",
      "release_date": "2023-08-17",
      "title": "スラムドッグス",
      "video": false,
      "vote_average": 7.5,
      "vote_count": 326
    },
    {
      "adult": false,
      "backdrop_path": "/qEm4FrkGh7kGoEiBOyGYNielYVc.jpg",
      "genre_ids": [53, 27],
      "id": 635910,
      "original_language": "en",
      "original_title": "The Last Voyage of the Demeter",
      "overview": "",
      "popularity": 384.873,
      "poster_path": "/tmQphfy9GYNqhHB9nqJPuigfw0x.jpg",
      "release_date": "2023-08-09",
      "title": "ドラキュラ／デメテル号最期の航海",
      "video": false,
      "vote_average": 7.4,
      "vote_count": 640
    },
    {
      "adult": false,
      "backdrop_path": "/9n2tJBplPbgR2ca05hS5CKXwP2c.jpg",
      "genre_ids": [16, 10751, 12, 14, 35],
      "id": 502356,
      "original_language": "en",
      "original_title": "The Super Mario Bros. Movie",
      "overview":
          "ニューヨークで配管工を営む双子の兄弟マリオとルイージ。謎の土管で迷いこんだのは、魔法に満ちた新世界。はなればなれになってしまった兄弟が、絆の力で世界の危機に立ち向かう。",
      "popularity": 400.317,
      "poster_path": "/4UVgwzJLfFk75QXbeIZDi8OQLAG.jpg",
      "release_date": "2023-04-05",
      "title": "ザ・スーパーマリオブラザーズ・ムービー",
      "video": false,
      "vote_average": 7.8,
      "vote_count": 6657
    },
    {
      "adult": false,
      "backdrop_path": "/AeR5k8Sp3zc2Ql4tT6CmgqspsEq.jpg",
      "genre_ids": [12, 10751, 14, 10749],
      "id": 447277,
      "original_language": "en",
      "original_title": "The Little Mermaid",
      "overview":
          "好奇心旺盛な人魚のアリエルは海の上の世界に憧れ、父親の意に反して地上へ飛び出す。王子や海の魔女との出会いや新しい冒険を通して本当の自分を見つけていく。",
      "popularity": 439.941,
      "poster_path": "/mWAoFDaRkAQLNHKgBkmEyM1p1uF.jpg",
      "release_date": "2023-05-18",
      "title": "リトル・マーメイド",
      "video": false,
      "vote_average": 6.6,
      "vote_count": 2051
    },
    {
      "adult": false,
      "backdrop_path": "/2a9DvjXQQezV0sWqJbIN2mDLgZZ.jpg",
      "genre_ids": [28, 18, 80],
      "id": 1093485,
      "original_language": "cn",
      "original_title": "掃毒3︰人在天涯",
      "overview": "",
      "popularity": 404.836,
      "poster_path": "/kPjZsEni0KF0IXGXh0kaxNESdGE.jpg",
      "release_date": "2023-07-06",
      "title": "掃毒3︰人在天涯",
      "video": false,
      "vote_average": 6.4,
      "vote_count": 14
    },
    {
      "adult": false,
      "backdrop_path": "/3mrli3xsGrAieQks7KsBUm2LpCg.jpg",
      "genre_ids": [28, 80, 53],
      "id": 979275,
      "original_language": "en",
      "original_title": "Mob Land",
      "overview": "",
      "popularity": 402.763,
      "poster_path": "/mcz8oi9oCgq1wkA3Wz2kluE94pE.jpg",
      "release_date": "2023-08-04",
      "title": "Mob Land",
      "video": false,
      "vote_average": 5.6,
      "vote_count": 22
    },
    {
      "adult": false,
      "backdrop_path": "/h0nmmdFAdBjQttN8Y0q825MWzZp.jpg",
      "genre_ids": [28, 53, 80],
      "id": 926393,
      "original_language": "en",
      "original_title": "The Equalizer 3",
      "overview":
          "ロバート・マッコール（デンゼル・ワシントン）は南イタリアで自宅で過ごしていた。しかし、友人達が地元の犯罪組織のボスの支配下にあることを知る。友人達がきっかけとなり、次第に事態が収拾のつかないトラベルへと発程していき、マッコールは自分が何をしなければならないかを理解していく。マフィアと対決して保護者になることを考えた結果、新たな戦いが幕をあける...",
      "popularity": 346.165,
      "poster_path": "/7lbleozncEZUtBCVy2UGSr5IvFH.jpg",
      "release_date": "2023-08-30",
      "title": "イコライザー THE FINAL",
      "video": false,
      "vote_average": 6.9,
      "vote_count": 205
    },
    {
      "adult": false,
      "backdrop_path": "/qZOuoBoKCDLSm1EvYz2eBub8Cto.jpg",
      "genre_ids": [16, 12, 14, 10751],
      "id": 939338,
      "original_language": "fr",
      "original_title": "Pattie et la colère de Poséidon",
      "overview": "",
      "popularity": 316.518,
      "poster_path": "/4B7BlaAfpfXrygeAj60KG3bcV6c.jpg",
      "release_date": "2023-01-25",
      "title": "Pattie et la colère de Poséidon",
      "video": false,
      "vote_average": 7,
      "vote_count": 28
    }
  ],
  "total_pages": 94,
  "total_results": 1867
};

const Map<String, dynamic> mockSearchPage1Response = {
  "page": 1,
  "results": [
    {
      "adult": false,
      "backdrop_path": null,
      "genre_ids": [],
      "id": 983331,
      "original_language": "zh",
      "original_title": "犬",
      "overview":
          "a series of retrospectives and interrogations after the death of a beloved dog.",
      "popularity": 0.6,
      "poster_path": null,
      "release_date": "",
      "title": "Dog",
      "video": false,
      "vote_average": 0.0,
      "vote_count": 0
    },
    {
      "adult": false,
      "backdrop_path": "/v4aulZlrAASAduoBw5ZYdsTR0E5.jpg",
      "genre_ids": [16, 14, 12],
      "id": 34295,
      "original_language": "ja",
      "original_title": "映画犬夜叉 天下覇道の剣",
      "overview":
          "犬夜叉が誕生した日、彼の父は妻を救うため人間の武士・刹那猛丸と死闘を繰り広げ、相討ちとなり果てた。その戦いで使われた妖刀は、刀々斎の手により骨喰いの井戸に放り込まれ処分された。  そして現代、日暮神社で発見されたその刀・叢雲牙の目覚めと共に、犬夜叉・殺生丸の兄弟は戦いへと誘われる。",
      "popularity": 23.145,
      "poster_path": "/gKFGQBKI1TnZ6foqoFgQruM86Mq.jpg",
      "release_date": "2003-12-20",
      "title": "犬夜叉 天下覇道の剣",
      "video": false,
      "vote_average": 7.775,
      "vote_count": 129
    },
    {
      "adult": false,
      "backdrop_path": "/40XTRnRRDZ4TzbjcrfW3WvtSsKW.jpg",
      "genre_ids": [28, 16, 12, 14],
      "id": 22537,
      "original_language": "ja",
      "original_title": "犬夜叉 鏡の中の夢幻城",
      "overview":
          "ついに宿敵・奈落を倒した犬夜叉。その直後から満月が何日も続き、奈落の分身・神無と神楽を利用して「天空の姫」と名乗る妖怪・神久夜が復活する。彼女はかつて弥勒の祖父によって封印された妖怪で「天女を喰らい、永遠の命を手に入れた」といい、かごめの神通力に目を付けて彼女を鏡の中の夢幻城に連れ去った。",
      "popularity": 19.253,
      "poster_path": "/oZ4tRe4P9ajEgDJT5HLvK3UbkyT.jpg",
      "release_date": "2002-12-22",
      "title": "犬夜叉 鏡の中の夢幻城",
      "video": false,
      "vote_average": 7.657,
      "vote_count": 134
    },
    {
      "adult": false,
      "backdrop_path": "/dEeclgUEcAOhBRwLjW58Qk6lRvi.jpg",
      "genre_ids": [14, 16, 12],
      "id": 34297,
      "original_language": "ja",
      "original_title": "犬夜叉 紅蓮の蓬莱島",
      "overview":
          "仲間との旅の途中、犬夜叉は半妖の少女に仲間を助けて欲しいと頼まれる。実は50年前に桔梗とともに行った不老不死の地、蓬莱島で、その少女と会っていたのだ。その少女をきっかけに、犬夜叉たちは四闘神との戦いに巻き込まれていく。",
      "popularity": 22.053,
      "poster_path": "/fu6eMjeOtD1dRw2sLL2xuwFRmLB.jpg",
      "release_date": "2004-12-23",
      "title": "犬夜叉 紅蓮の蓬莱島",
      "video": false,
      "vote_average": 7.49,
      "vote_count": 99
    },
    {
      "adult": false,
      "backdrop_path": "/aWg40fkUvghFwrCya2fHvAEvjud.jpg",
      "genre_ids": [28, 16, 12, 14],
      "id": 42360,
      "original_language": "ja",
      "original_title": "犬夜叉 時代を越える想い",
      "overview":
          "15歳の誕生日に境内の井戸から戦国時代にタイムスリップした日暮かごめは、半妖怪・犬夜叉の封印を解いてしまう。こうして出会った二人は、妖力を秘めた“四魂の玉”のかけらをめぐって邪悪な妖怪たちとの戦いを繰り広げていく。だが新たに現れた大陸妖怪軍団の首領・瑪瑙丸の狙いは“四魂の玉”ではなく、犬夜叉が持つ鉄砕牙と呼ばれる剣だった。瑠璃と玻璃の美少女妖怪を従えた瑪瑙丸は、実はかつて犬夜叉の父と死闘の末に封印された過去を持っていたのだ。そして犬夜叉とかごめが出会った御神木にも隠された秘密が存在していた。",
      "popularity": 24.504,
      "poster_path": "/vFKtOW2vlEIW1A4ZN60HFW8Axhu.jpg",
      "release_date": "2001-12-15",
      "title": "犬夜叉 時代を越える想い",
      "video": false,
      "vote_average": 7.62,
      "vote_count": 171
    },
    {
      "adult": false,
      "backdrop_path": "/96sS0woEzf0zFSWjHVblOhsBfGd.jpg",
      "genre_ids": [18, 10749, 35, 10751],
      "id": 522924,
      "original_language": "en",
      "original_title": "The Art of Racing in the Rain",
      "overview":
          "A family dog – with a near-human soul and a philosopher's mind – evaluates his life through the lessons learned by his human owner, a race-car driver.",
      "popularity": 40.243,
      "poster_path": "/mi5VN4ww0JZgRFJIaPxxTGKjUg7.jpg",
      "release_date": "2019-08-08",
      "title": "エンツォ レーサーになりたかった犬とある家族の物語",
      "video": false,
      "vote_average": 8.217,
      "vote_count": 1298
    },
    {
      "adult": false,
      "backdrop_path": "/lkBwfDDgLw1giIdmJCbVObkTzFr.jpg",
      "genre_ids": [16, 12, 10751],
      "id": 82703,
      "original_language": "en",
      "original_title": "Mr. Peabody \u0026 Sherman",
      "overview":
          "言葉が話せ、人間以上の知能を誇る天才犬ピーボ博士と、養子になった人間の少年シャーマン。2人は実の親子以上の絆で結ばれていた。だがある日、シャーマンが学校で同級生の少女ペニーとトラブルを起こしてしまう。博士はペニーと両親を自宅に招き、和解するためのパーティーを開くのだが、そのさなか博士がタイムマシンを発明したことを知ったペニーが、勝手にマシンを使って古代エジプトへとタイムトラベルしてしまう。",
      "popularity": 24.625,
      "poster_path": "/AtEFqJSvDXoNSF8mIdqoh9ectwh.jpg",
      "release_date": "2014-02-07",
      "title": "天才犬ピーボ博士のタイムトラベル",
      "video": false,
      "vote_average": 6.735,
      "vote_count": 2191
    },
    {
      "adult": false,
      "backdrop_path": "/jB5zHG1eHh0OC1S61itXNApZlLD.jpg",
      "genre_ids": [12, 35, 16],
      "id": 399174,
      "original_language": "en",
      "original_title": "Isle of Dogs",
      "overview":
          "近未来の日本。ドッグ病が大流行するメガ崎市では、人間への感染を恐れた小林市長が、すべての犬を“犬ヶ島”に追放する。ある時、12歳の少年がたった一人で小型飛行機に乗り込み、その島に向かった。愛犬で親友のスポッツを救うためにやって来た、市長の養子で孤児のアタリだ。島で出会った勇敢で心優しい5匹の犬たちを新たな相棒とし、スポッツの探索を始めたアタリは、メガ崎の未来を左右する大人たちの陰謀へと近づいていく─。",
      "popularity": 25.409,
      "poster_path": "/kE8YgujIKaEU2xPeht14fzR8k1U.jpg",
      "release_date": "2018-03-23",
      "title": "犬ヶ島",
      "video": false,
      "vote_average": 7.858,
      "vote_count": 4412
    },
    {
      "adult": false,
      "backdrop_path": "/sZV8aQJlym7AiBcE1H3ISEGoVVw.jpg",
      "genre_ids": [27, 9648],
      "id": 635199,
      "original_language": "ja",
      "original_title": "犬鳴村",
      "overview":
          "臨床心理士の森田奏の周りで突如、奇妙な出来事が起こり始める。\r 「わんこがねぇやに ふたしちゃろ～♪」奇妙なわらべ歌を歌い出しおかしくなった女性、行方不明になった兄弟、そして、繰り返される不可解な変死。\r それらの共通点は心霊スポット【犬鳴トンネル】だった。突然死した女性が死の直後に残した言葉「トンネルを抜けた先に村があって、そこで●●を見た・・・」\r これは、一体どんな意味なのか？\r 全ての真相を突き止めるため、奏は犬鳴トンネルに向かう。しかしその先には、決して踏み込んではいけない、驚愕の真相があった・・・。\r 身も凍る恐怖と戦慄、古より続く血の祝祭からあなたは逃げられない。",
      "popularity": 13.853,
      "poster_path": "/i9a1FQGW8u4jW4KIEGVCkaAvcQ9.jpg",
      "release_date": "2020-02-07",
      "title": "犬鳴村",
      "video": false,
      "vote_average": 5.974,
      "vote_count": 77
    },
    {
      "adult": false,
      "backdrop_path": "/tVoWbAAfTDIhTeo78SbA2V6mv8E.jpg",
      "genre_ids": [35, 10751],
      "id": 14306,
      "original_language": "en",
      "original_title": "Marley \u0026 Me",
      "overview":
          "子育ての予行演習のつもりで犬を飼い始めた新婚夫婦と、ラブラドール・レトリバーの愛ときずなを描く感動作。愛犬との生活を通し、結婚生活をめぐる普遍的な悩みや問題を描き出したベストセラー・エッセーを映画化。監督は『プラダを着た悪魔』のデヴィッド・フランケル。主人公夫婦を『ダージリン急行』のオーウェン・ウィルソンと「フレンズ」のジェニファー・アニストンが演じている。泣いて笑って、最後は温かい気持ちになれる一作。",
      "popularity": 23.123,
      "poster_path": "/pgnXqGLTB7LqCIJbSnYuxpCpTb2.jpg",
      "release_date": "2008-12-25",
      "title": "マーリー 世界一おバカな犬が教えてくれたこと",
      "video": false,
      "vote_average": 7.198,
      "vote_count": 4309
    },
    {
      "adult": false,
      "backdrop_path": "/exOykaBLLT2hc0zvYrZz0yz5Asz.jpg",
      "genre_ids": [16, 18, 10402],
      "id": 642538,
      "original_language": "ja",
      "original_title": "犬王",
      "overview":
          "室町の京の都、猿楽の一座に生まれた異形の子、犬王。周囲に疎まれ、その顔は瓢箪の面で隠された。\r ある日犬王は、平家の呪いで盲目になった琵琶法師の少年・友魚と出会う。名よりも先に、歌と舞を交わす二人。 友魚は琵琶の弦を弾き、犬王は足を踏み鳴らす。一瞬にして拡がる、二人だけの呼吸、二人だけの世界。\r 「ここから始まるんだ俺たちは！」\r 壮絶な運命すら楽しみ、力強い舞で自らの人生を切り拓く犬王。呪いの真相を求め、琵琶を掻き鳴らし異界と共振する友魚。乱世を生き抜くためのバディとなった二人は、お互いの才能を開花させ、唯一無二のエンターテイナーとして人々を熱狂させていく。頂点を極めた二人を待ち受けるものとは――？\r 歴史に隠された実在の能楽師＝ポップスター・犬王と友魚から生まれた、時を超えた友情の物語",
      "popularity": 14.99,
      "poster_path": "/96mbrDL8CiCJSmNH6Fd1BP6IFhj.jpg",
      "release_date": "2022-05-28",
      "title": "犬王",
      "video": false,
      "vote_average": 7.5,
      "vote_count": 55
    },
    {
      "adult": false,
      "backdrop_path": "/zJ2uTOvMJOZu97L1EVo5HqdEdsN.jpg",
      "genre_ids": [28, 80, 9648],
      "id": 451997,
      "original_language": "ko",
      "original_title": "불한당: 나쁜 놈들의 세상",
      "overview":
          "Jae-ho, who aims to become the number one in a crime organization, gets to build up trust with Hyun-su, an ambitious newbie in the prison. While they try to take over the organization after the prison release, their ulterior motives starts to emerge.",
      "popularity": 20.557,
      "poster_path": "/dMNGy8kfySmmNDHw3X4puqPIbx8.jpg",
      "release_date": "2017-05-17",
      "title": "名もなき野良犬の輪舞",
      "video": false,
      "vote_average": 7.124,
      "vote_count": 109
    },
    {
      "adult": false,
      "backdrop_path": "/2ybWIHxrJxQZ1IJIM9gqpKuesIU.jpg",
      "genre_ids": [14, 12, 18, 28],
      "id": 47578,
      "original_language": "ja",
      "original_title": "里見八犬伝",
      "overview":
          "かつて素藤の父に輿入れし蟇田領で酒池肉林と暴虐の限りを尽くした玉梓 (たまづさ) は、里見家に討ち滅ぼされた怨念を晴らすために妖怪の首領として蘇えり、息子の蟇田素藤 (ひきたもとふじ) と家来に命じ、里見家の館山城に攻め入った。里見家は滅ぼされ、静姫と一部の家来は生き延びるが、玉梓の追手が迫ってくる。伏姫の体から飛び散った、仁・義・礼・智・忠・信・孝・悌の各字を刻んだ八つの霊玉を持った八剣士は、それぞれの立場で生きていた。やがて彼らは運命に導かれ、静姫のもとに集まり、玉梓の野望を砕くため、戦いを挑む。",
      "popularity": 5.336,
      "poster_path": "/8pSc9IId5nzI8hhUsy1tdHOtPms.jpg",
      "release_date": "1983-12-10",
      "title": "里見八犬伝",
      "video": false,
      "vote_average": 5.818,
      "vote_count": 22
    },
    {
      "adult": false,
      "backdrop_path": "/rZEEoQqUMPHdvtt8YzpfZ9TGNwa.jpg",
      "genre_ids": [18, 10751, 12],
      "id": 125239,
      "original_language": "ja",
      "original_title": "マリと子犬の物語",
      "overview":
          "新潟県中越地震発生時の実話を基に、被災地に取り残されながらも、産んだばかりの子犬たちを必死で守り抜こうとする母犬の奮闘を描いた感動作。新潟県山古志村で暮らす石川家に、新しい家族がやって来る。小学生の亮太と妹の彩が子犬を拾ってきたのだ。“マリ”と名付けられたその子犬はすくすくと成長し、やがて3匹の子を産む。しかし、新しい命の誕生に喜んだのもつかの間、村をマグニチュード6.8の大地震が襲い……。",
      "popularity": 4.41,
      "poster_path": "/nRk03qDsiXo0QCylQsUcXxNloMM.jpg",
      "release_date": "2007-12-08",
      "title": "マリと子犬の物語",
      "video": false,
      "vote_average": 7.8,
      "vote_count": 9
    },
    {
      "adult": false,
      "backdrop_path": "/yzf3b8zFC2ol90eGL0VySETR94K.jpg",
      "genre_ids": [12, 18, 10751],
      "id": 2202,
      "original_language": "en",
      "original_title": "Lassie Come Home",
      "overview":
          "Hard times come for the Carraclough family and they are forced to sell their dog, Lassie, to the rich Duke of Rudling. Lassie, however, is unwilling to remain apart from young Carraclough son Joe and sets out on a long and dangerous journey to rejoin him.",
      "popularity": 16.336,
      "poster_path": "/boMs7uR8yJEnHKSvzkszS6eenmz.jpg",
      "release_date": "1943-12-01",
      "title": "名犬ラッシー 家路",
      "video": false,
      "vote_average": 6.691,
      "vote_count": 115
    },
    {
      "adult": false,
      "backdrop_path": "/ggVe1eacxS4D0Z805Liqecj6zHi.jpg",
      "genre_ids": [12, 18, 10751],
      "id": 14597,
      "original_language": "en",
      "original_title": "Lassie",
      "overview":
          "エリック・ナイトの原作を豪華キャストで映画化した、少年と犬の友情ストーリー。9歳の少年ジョーとその親友のコリー犬・ラッシー。だが、生活に困った両親がラッシーを公爵に売ってしまう。ラッシーは何度もジョーのもとに戻ろうとするが……。",
      "popularity": 9.929,
      "poster_path": "/qB7NcROV5GzWLhHyFjSobPq9Eue.jpg",
      "release_date": "2005-12-16",
      "title": "名犬ラッシー",
      "video": false,
      "vote_average": 6.446,
      "vote_count": 121
    },
    {
      "adult": false,
      "backdrop_path": "/I6rNAQ0wzFOtLgGuD7BLCyAih6.jpg",
      "genre_ids": [35, 80, 18],
      "id": 21531,
      "original_language": "ko",
      "original_title": "플란다스의 개",
      "overview":
          "閑静なマンション団地で発生した連続子犬失踪事件を、OLとその親友が追う、韓国発のエンタテインメント・ムービー。シュールなシチュエーションとトボけたキャラクターが楽しい。",
      "popularity": 13.594,
      "poster_path": "/kjVEpWOGKmA1xdU9dp8zj2VBc3.jpg",
      "release_date": "2000-02-19",
      "title": "ほえる犬は噛まない",
      "video": false,
      "vote_average": 6.822,
      "vote_count": 216
    },
    {
      "adult": false,
      "backdrop_path": "/1Wlwnhn5sXUIwlxpJgWszT622PS.jpg",
      "genre_ids": [10751, 12, 35, 14],
      "id": 585245,
      "original_language": "en",
      "original_title": "Clifford the Big Red Dog",
      "overview":
          "ノーマン・ブリッドウェルによる世界的人気の絵本シリーズ『クリフォード』を実写映画化。転校先になじめず、孤独を感じていた少女が真っ赤な子イヌと出会うが、なんと一夜にして3ｍ以上に巨大化してしまい……。",
      "popularity": 53.604,
      "poster_path": "/oifhfVhUcuDjE61V5bS5dfShQrm.jpg",
      "release_date": "2021-11-10",
      "title": "でっかくなっちゃった赤い子犬 僕はクリフォード",
      "video": false,
      "vote_average": 7.2,
      "vote_count": 1613
    },
    {
      "adult": false,
      "backdrop_path": "/pKeatSUHRrlcTmkAOQ9tvESbCCe.jpg",
      "genre_ids": [80, 18, 53],
      "id": 30368,
      "original_language": "ja",
      "original_title": "野良犬",
      "overview":
          "暑い夏の日の午後だった。若い村上刑事は射撃訓練の帰り道、満員のバスの中でコルトを盗まれ、犯人を追ったが路地裏で見失った。そのコルトには7発の実弾が装てんされていたため、もしやこの銃を使って事件が起こるのでは、と村上は悩む。村上はスリ係の老刑事と、捜査線上に浮んだお銀という女を訪ね、なんとか貸しピストル屋を聞き出し、そこからさらに本多という男を捜し当てる。村上はベテラン刑事・佐藤と満員の後楽園球場に乗り込み、本多をおびき出す。逮捕された本多は、仲間の遊佐が拳銃を持っていると白状する。こうして村上と佐藤は遊佐を追いつめていくが、ついに村上のコルトによる強盗事件が起きてしまう…。",
      "popularity": 10.503,
      "poster_path": "/tr4zUsfuGMkylUJ5h4jCDT1dhBC.jpg",
      "release_date": "1949-10-17",
      "title": "野良犬",
      "video": false,
      "vote_average": 7.487,
      "vote_count": 261
    },
    {
      "adult": false,
      "backdrop_path": "/kxjGNQVB7bvWQSisIOEgTT2TXp.jpg",
      "genre_ids": [35, 18],
      "id": 326094,
      "original_language": "en",
      "original_title": "Wiener-Dog",
      "overview":
          "A dachshund passes from oddball owner to oddball owner, whose radically dysfunctional lives are all impacted by the pooch.",
      "popularity": 8.087,
      "poster_path": "/borMbLGZWX7C72WqKNJVEOXrYOf.jpg",
      "release_date": "2016-06-24",
      "title": "トッド・ソロンズの子犬物語",
      "video": false,
      "vote_average": 5.646,
      "vote_count": 188
    }
  ],
  "total_pages": 18,
  "total_results": 356
};
const Map<String, dynamic> mockSearchPage2Response = {
  "page": 2,
  "results": [
    {
      "adult": false,
      "backdrop_path": "/8xpVDoRy0fZzhMSUBG8nksctu9i.jpg",
      "genre_ids": [35],
      "id": 335970,
      "original_language": "en",
      "original_title": "Joe Dirt 2: Beautiful Loser",
      "overview":
          "When happy family man Joe Dirt finds himself transported to the recent past, he begins an epic journey to get back to his loved ones in the present.",
      "popularity": 13.731,
      "poster_path": "/nde744Wjaj11BXA4npXcByLDMkw.jpg",
      "release_date": "2015-07-16",
      "title": "ジョー・ダート 華麗なる負け犬の伝説",
      "video": false,
      "vote_average": 4.953,
      "vote_count": 138
    },
    {
      "adult": false,
      "backdrop_path": "/lNmIAX1IuPIEPMHhLBEm4wmhYX0.jpg",
      "genre_ids": [12, 16, 18, 10751],
      "id": 10948,
      "original_language": "en",
      "original_title": "The Fox and the Hound",
      "overview":
          "母親を猟師に殺され、ふくろうのビッグママの計らいによって心優しいトゥード未亡人の家で育てられることになった子ぎつねトッド。ある日、トッドは、近くに住む猟師の家で猟犬の子コッパーに出会い、すぐに仲良しになる。だが、成長したトッドは野生に返されることになり、一方のコッパーも一人前の猟犬として訓練を受けることになった。やがて2匹は森の中で再会を果たすが、もはや彼らは敵同士となっていた。",
      "popularity": 33.107,
      "poster_path": "/15OGr9EggUzV33SFY2sO3nokRPX.jpg",
      "release_date": "1981-07-10",
      "title": "きつねと猟犬",
      "video": false,
      "vote_average": 7.13,
      "vote_count": 2958
    },
    {
      "adult": false,
      "backdrop_path": "/xWQ6A4HvknjHlFw4R9FyQDFg9ma.jpg",
      "genre_ids": [10751, 35],
      "id": 18500,
      "original_language": "en",
      "original_title": "The Sandlot 2",
      "overview":
          "A decade has passed in the small town where the original Sandlot gang banded together during the summer of ’62 to play baseball and battle the Beast. Now comes the sequel, a campy romp back to the dugout where nine new kids descend on the diamond only to discover that a descendant of the Beast lives in Mr. Mertle’s backyard--a monster of mythical proportions known as \"The Great Fear.\"",
      "popularity": 11.057,
      "poster_path": "/xLc3jTAKAOCg7lBWp9vzyAJNLay.jpg",
      "release_date": "2005-11-10",
      "title": "わるわる探犬隊",
      "video": false,
      "vote_average": 5.785,
      "vote_count": 144
    },
    {
      "adult": false,
      "backdrop_path": "/j6izee2sNjefaFb2haOfbcKjaGc.jpg",
      "genre_ids": [35],
      "id": 36208,
      "original_language": "en",
      "original_title": "A Dog's Life",
      "overview":
          "The Tramp and his dog companion struggle to survive in the inner city.",
      "popularity": 6.651,
      "poster_path": "/41vqtliesQrsJQ9iTJh5nFYQgBg.jpg",
      "release_date": "1918-04-14",
      "title": "犬の生活",
      "video": false,
      "vote_average": 7.365,
      "vote_count": 289
    },
    {
      "adult": false,
      "backdrop_path": "/2xyyn4Rc9kbkaojG9am1FInCmxr.jpg",
      "genre_ids": [16, 35, 18, 10751],
      "id": 293299,
      "original_language": "en",
      "original_title": "Feast",
      "overview":
          "This Oscar-winning animated short film tells the story of one man's love life as seen through the eyes of his best friend and dog, Winston, and revealed bite by bite through the meals they share.",
      "popularity": 8.049,
      "poster_path": "/6hAgSxgd2YIK5pYhwowtnlGpwbe.jpg",
      "release_date": "2014-10-25",
      "title": "愛犬とごちそう",
      "video": false,
      "vote_average": 7.833,
      "vote_count": 810
    },
    {
      "adult": false,
      "backdrop_path": "/psOtyMIfeSJebpeKiDUR1M6wto2.jpg",
      "genre_ids": [80, 18],
      "id": 14375,
      "original_language": "it",
      "original_title": "Romanzo criminale",
      "overview":
          "After serving prison time for a juvenile offense, Freddo gathers his old buddies Libano and Dandi and embarks on a crime spree that makes the trio the most powerful gangsters in Rome. Libano loves their new status, and seeks to spread their influence throughout the underworld, while the other two pursue more fleshly desires. For decades, their gang perpetrates extravagant crimes, until paranoia threatens to split the friends apart.",
      "popularity": 12.508,
      "poster_path": "/jd06ZOSBpjfKEthqli5O2urO0nm.jpg",
      "release_date": "2005-09-30",
      "title": "野良犬たちの掟",
      "video": false,
      "vote_average": 7.195,
      "vote_count": 611
    },
    {
      "adult": false,
      "backdrop_path": "/x8JRhQnQpanaSjQK3UaHDUKE29m.jpg",
      "genre_ids": [18, 10751],
      "id": 28178,
      "original_language": "en",
      "original_title": "Hachi: A Dog's Tale",
      "overview":
          "アメリカ、郊外のベッドリッジ駅。寒い冬の夜に、迷い犬になった秋田犬の子犬を保護したパーカー・ウィルソン教授（リチャード・ギア）は、妻ケイト（ジョーン・アレン）の反対を押し切って子犬を飼うことに。首輪のタグに刻まれていた漢字から、ハチと名づけられた子犬は、パーカーの愛情を受けてすくすくと成長していく。",
      "popularity": 32.991,
      "poster_path": "/zxLyV6Lg2aedopcCX6gLfQlc7NP.jpg",
      "release_date": "2009-06-08",
      "title": "HACHI 約束の犬",
      "video": false,
      "vote_average": 8.007,
      "vote_count": 6224
    },
    {
      "adult": false,
      "backdrop_path": "/tMkLwH4mM6v751wG67iSSRtYxm7.jpg",
      "genre_ids": [12, 16, 35, 10751],
      "id": 9948,
      "original_language": "en",
      "original_title": "The Fox and the Hound 2",
      "overview":
          "小さな頃から大の仲良しの子ぎつねトッドと子犬のコッパー。ある日、一緒に村のお祭りにでかけた2匹は、犬たちのコーラスグループのステージを見る。そこでたまたま舞台に上がって歌ったコッパーは、グループのメンバーにスカウトされて大喜び。すっかり人気者となりスター気分のコッパーだったが、トッドとの大切な約束を忘れてしまう。すれ違ってしまった2匹の友情は、どうなってしまうのか・・・。",
      "popularity": 26.995,
      "poster_path": "/uTrVvEtN4Gq7l0Zxd8KRYyiTvm3.jpg",
      "release_date": "2006-11-09",
      "title": "きつねと猟犬2 トッドとコッパーの大冒険",
      "video": false,
      "vote_average": 6.016,
      "vote_count": 607
    },
    {
      "adult": false,
      "backdrop_path": null,
      "genre_ids": [9648, 53],
      "id": 76759,
      "original_language": "ja",
      "original_title": "犬神家の一族",
      "overview":
          "信州の犬神財閥の創始者である犬神佐兵衛（仲代達矢）は、腹違いの3人の娘とその息子たち、佐兵衛の大恩人の孫娘、野々宮珠世（松嶋菜々子）らを残してこの世を去る。巨額の遺産が一族の争いの元凶となることを予期した法律事務所の若林は金田一耕助（石坂浩二）に調査を依頼するが、ほどなく一族間で次々と殺人事件が発生する。",
      "popularity": 4.456,
      "poster_path": "/ofaUbYTyZsJqj1sKZYDKfAbTvL.jpg",
      "release_date": "2006-12-16",
      "title": "犬神家の一族",
      "video": false,
      "vote_average": 6.444,
      "vote_count": 9
    },
    {
      "adult": false,
      "backdrop_path": null,
      "genre_ids": [27],
      "id": 79624,
      "original_language": "ja",
      "original_title": "犬神の悪霊",
      "overview":
          "日本各地に残る犬神憑きや狐憑き伝説。その憑き物を代表する“犬神憑き”に題材を取って、現代の都会と山村で次々と起る怪奇現象と取り憑く身の毛もよだつ恐怖を、リアルで大胆な映像感覚で描いたカルト的名声高いホラー大作。とくに犬神が可憐な少女に憑依して天空を疾駆する息もつかせないバトルは見応え十分である。",
      "popularity": 2.395,
      "poster_path": "/qBJfmLCtczkayFXduwhFvX9vsZm.jpg",
      "release_date": "1977-06-18",
      "title": "犬神の悪霊",
      "video": false,
      "vote_average": 6.7,
      "vote_count": 3
    },
    {
      "adult": false,
      "backdrop_path": "/6skXJ51qD2pzCTegs5bgjun5lhV.jpg",
      "genre_ids": [18, 35],
      "id": 529866,
      "original_language": "ja",
      "original_title": "犬猿",
      "overview":
          "印刷会社で営業を担当している金山和成（窪田正孝）は、刑務所から出てきたばかりの乱暴者の兄・卓司（新井浩文）を恐れていた。一方、幾野由利亜（江上敬子）と、芸能活動をしているおバカな妹の真子（筧美和子）は、家業の印刷工場を切り盛りしていた。兄弟と姉妹の関係は、あるときから変化し始め……。",
      "popularity": 2.929,
      "poster_path": "/8T79DKyyEvxw84ARmt3ztQr10Wg.jpg",
      "release_date": "2018-02-10",
      "title": "犬猿",
      "video": false,
      "vote_average": 6.8,
      "vote_count": 5
    },
    {
      "adult": false,
      "backdrop_path": "/mU1fS2ElfwBEEctPCaxtgIle5fF.jpg",
      "genre_ids": [10751, 12, 18],
      "id": 61856,
      "original_language": "en",
      "original_title": "Courage of Lassie",
      "overview":
          "Bill's separated from his litter, making friends with the wild creatures until he's found and adopted by young Kathie. An accident separates him from her, and he's drafted into K-9 duty in the trenches until battle fatigue takes its toll and he turns vicious. And even though he finds his way back home, he may be condemned as a killer.",
      "popularity": 5.924,
      "poster_path": "/gRff56Vpe3xw9I94k7gFa2NR68s.jpg",
      "release_date": "1946-11-08",
      "title": "名犬ラッシー／ラッシーの勇気",
      "video": false,
      "vote_average": 5.643,
      "vote_count": 28
    },
    {
      "adult": false,
      "backdrop_path": null,
      "genre_ids": [35, 18],
      "id": 85476,
      "original_language": "ja",
      "original_title": "犬とあなたの物語 いぬのえいが",
      "overview":
          "「犬の名前」…子どもの頃に飼い犬が死んで以来、犬嫌いになってしまった一郎。しかし妻の美里は、そんな夫にお構いなしに大型犬をもらってきてしまう。とても頭の良い犬に、徐々に心を開いていく一郎。だがそんな矢先、一郎の身に“ある異変”が起き始める…。「お母さんは心配性」…息子の結婚披露宴中に、初めてのお留守番をさせてきた愛犬が心配でたまらなくなった美知代は…!?　「バニラのかけら」…愛犬を亡くした悲しみからいつまで経っても立ち直れない奈津子は、ある日、公園でかつての愛犬そっくりの犬と出会う。…ほか3篇。",
      "popularity": 1.715,
      "poster_path": "/cQH89uDoOu4FOsP6ZUFbSPijUiD.jpg",
      "release_date": "2011-01-22",
      "title": "犬とあなたの物語 いぬのえいが",
      "video": false,
      "vote_average": 8.0,
      "vote_count": 1
    },
    {
      "adult": false,
      "backdrop_path": null,
      "genre_ids": [],
      "id": 356811,
      "original_language": "ja",
      "original_title": "切り裂きジャックの告白　～刑事　犬養隼人～",
      "overview":
          "『切り裂きジャックの告白』（きりさきジャックのこくはく）は、中山七里の推理小説。『切り裂きジャックの告白 〜刑事 犬養隼人〜』（きりさきジャックのこくはく けいじ いぬかいはやと）のタイトルで2015年4月18日にテレビ朝日系で「土曜ワイド劇場特別企画」としてテレビドラマ化された。主演は沢村一樹。テレビ局名がオリジナルでは「帝都テレビ」だが、ドラマでは「関東中央テレビ」となっている。",
      "popularity": 1.488,
      "poster_path": null,
      "release_date": "2015-04-18",
      "title": "切り裂きジャックの告白 〜刑事 犬養隼人〜",
      "video": false,
      "vote_average": 0.0,
      "vote_count": 0
    },
    {
      "adult": false,
      "backdrop_path": "/2kjFwdI6s5RnqXWuEmg54nUZopc.jpg",
      "genre_ids": [16, 18, 10749],
      "id": 48661,
      "original_language": "ja",
      "original_title": "フランダースの犬",
      "overview":
          "19世紀のベルギーのフランダース地方。アントワープにある大聖堂を一人の修道女が訪れる。彼女は、聖堂に飾られている大画家ルーベンスの｢聖母被昇天｣を仰ぎ見るうち、その記憶は20年前へとさかのぼる。おじいさんと牛乳運びで生計を立てる少年ネロと愛犬パトラッシュは貧しいながらも幸せに暮らしていた。ネロの夢はルーベンスのような画家になること。そんなネロのささやかだが幸せな日々は長くは続かなかった。",
      "popularity": 3.733,
      "poster_path": "/2Bp0LW1VR2q1kf3lomlJ6WpaTJn.jpg",
      "release_date": "1997-03-15",
      "title": "劇場版 フランダースの犬",
      "video": false,
      "vote_average": 7.9,
      "vote_count": 19
    },
    {
      "adult": false,
      "backdrop_path": "/8eWzglk0uHAtbFgKb3lVTXnJvxp.jpg",
      "genre_ids": [18, 53],
      "id": 994,
      "original_language": "en",
      "original_title": "Straw Dogs",
      "overview":
          "David Sumner, a mild-mannered academic from the United States, marries Amy, an Englishwoman. In order to escape a hectic stateside lifestyle, David and his wife relocate to the small town in rural Cornwall where Amy was raised. There, David is ostracized by the brutish men of the village, including Amy's old flame, Charlie. Eventually the taunts escalate, and two of the locals rape Amy. This sexual assault awakes a shockingly violent side of David.",
      "popularity": 15.027,
      "poster_path": "/yigkfHE1OhkxPPrjrV78Y9ibGEk.jpg",
      "release_date": "1971-12-23",
      "title": "わらの犬",
      "video": false,
      "vote_average": 7.138,
      "vote_count": 832
    },
    {
      "adult": false,
      "backdrop_path": "/pmU8YduNooV6bZ3rynWbPndmkIR.jpg",
      "genre_ids": [10751, 35, 18],
      "id": 136984,
      "original_language": "en",
      "original_title": "The Duke",
      "overview":
          "When his nephew tries to wrest control of his estate from him, the Duke of Dingwall removes the boy from his will and leaves everything to his dog.",
      "popularity": 7.219,
      "poster_path": "/qTU1WgVGUWNJm2H19tHvZrwDN6H.jpg",
      "release_date": "1999-01-01",
      "title": "犬いなる遺産",
      "video": false,
      "vote_average": 4.1,
      "vote_count": 17
    },
    {
      "adult": false,
      "backdrop_path": "/jQywhaFDVLPlFw864Bgw5eNtWfi.jpg",
      "genre_ids": [14],
      "id": 626,
      "original_language": "fr",
      "original_title": "Un chien andalou",
      "overview":
          "Un Chien Andalou is an European avant-garde surrealist film, a collaboration between director Luis Buñuel and Salvador Dali.",
      "popularity": 19.49,
      "poster_path": "/obvE7ElAvCUhKtWFwDSvNbPw9PV.jpg",
      "release_date": "1929-06-05",
      "title": "アンダルシアの犬",
      "video": false,
      "vote_average": 7.5,
      "vote_count": 1157
    },
    {
      "adult": false,
      "backdrop_path": "/4e0qQpyIyzZ9kyB6ZkjGb6XOWpS.jpg",
      "genre_ids": [9648, 53, 27],
      "id": 11791,
      "original_language": "en",
      "original_title": "The Hound of the Baskervilles",
      "overview":
          "When a nobleman is threatened by a family curse on his newly inherited estate, detective Sherlock Holmes is hired to investigate.",
      "popularity": 12.654,
      "poster_path": "/gJNscfPsBnQRdIjjdrTIHVCRwvY.jpg",
      "release_date": "1959-05-04",
      "title": "バスカヴィル家の犬",
      "video": false,
      "vote_average": 6.868,
      "vote_count": 280
    },
    {
      "adult": false,
      "backdrop_path": "/vRT2Iend2CzgvpDyFRWK51l2tuY.jpg",
      "genre_ids": [9648, 80],
      "id": 886024,
      "original_language": "ja",
      "original_title": "バスカヴィル家の犬 シャーロック劇場版",
      "overview":
          "瀬戸内海の離島。日本有数の資産家が、莫大な遺産を遺して謎の変死を遂げる。資産家は死の直前、美しき娘の誘拐未遂事件の犯人捜索を若宮に依頼していた。真相を探るため、ある閉ざされた島に降り立つ獅子雄と若宮。二人を待ち受けていたのは、異様な佇まいの洋館と、犬の遠吠え。容疑者は、奇妙で華麗な一族の面々と、うそを重ねる怪しき関係者たち。やがて島に伝わる呪いが囁かれると、新たな事件が連鎖し、一人、また一人消えてゆく。底なし沼のような罠におちいる若宮。謎解きを後悔する獅子雄。これは開けてはいけない“パンドラの箱”だったのか？その屋敷に、足を踏み入れてはいけない―― 。終わらない謎へ、ようこそ。",
      "popularity": 2.795,
      "poster_path": "/63LH5elZ8XEzGAaD6ZjxUZKVjPZ.jpg",
      "release_date": "2022-06-17",
      "title": "バスカヴィル家の犬 シャーロック劇場版",
      "video": false,
      "vote_average": 7.0,
      "vote_count": 2
    }
  ],
  "total_pages": 18,
  "total_results": 356
};
const Map<String, dynamic> mockNoResultResponse = {
  "page": 1,
  "results": [],
  "total_pages": 1,
  "total_results": 0
};
