name: Flutter_Test

#on: ワークフローの起動条件
on:
  #プルリク作成/更新時
  pull_request:
    types: [opened, synchronize]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

#環境変数読み込み
env:
  API_KEY: ${{secrets.API_KEY}}

# 複数のジョブを定義
jobs:
  #unit test/golden test
  flutter_test_macos:
    name: Flutter Test (macos)
    #ローカルと同じのmac環境を準備する
    runs-on: macos-13
    timeout-minutes: 10
    
    #ジョブの手順
    steps:
      #ソースコードを取得
      - name: Checkout
        uses: actions/checkout@v3
        with:
          #fetch-depth を指定しないと、
          #push 直前のコミットが取得できない
          fetch-depth: 1
      - name: Flutter Setup
        uses: ./.github/actions/build
      #テスト
      - name: Run Flutter Test
        run: flutter test
  #integration test(ios)
  flutter_integration_test_ios:
    name: Flutter Integration Test (IOS)
    runs-on: macos-latest
    timeout-minutes: 20
    strategy:
      matrix:
        device:
          - "iPhone 14 Simulator (16.2)" 
      fail-fast: false
    steps:
      - name: "List all simulators"
        run: "xcrun xctrace list devices"
      #grep "^${{ matrix.device }}"
      #->matrix.deviceで指定されたデバイス名）に一致するデータを抽出
      #grep -v "Apple Watch"
      #->シミュレータの一覧からApple Watchを除外
      #awk '{gsub(/[()]/,""); print $NF}':
      #->括弧（()）を削除し、最後のフィールド（デバイスのUDID）を抽出
      #xcrun simctl boot: 指定されたUDIDを持つiOSシミュレータを起動
      - name: "Start Simulator"
        run: |
          UDID=$(xcrun xctrace list devices | grep "^${{ matrix.device }}" | grep -v "Apple Watch" | awk '{gsub(/[()]/,""); print $NF}')
          echo $UDID
          xcrun simctl boot "${UDID:?No Simulator with this name found}"
      #ソースコードを取得
      - name: Checkout
        uses: actions/checkout@v3
        with:
          #fetch-depth を指定しないと、
          #push 直前のコミットが取得できない
          fetch-depth: 1
      - name: Flutter Setup
        uses: ./.github/actions/build
      #統合テスト
      - name: Integration Test(ios)
        run: flutter test integration_test
  
  flutter_integration_test_android:
    name: Flutter Integration Test (Android)
    runs-on: macos-latest
    timeout-minutes: 20
    strategy:
      matrix:
        api-level:
          - 29
      fail-fast: true
    steps:
      #ソースコードを取得
      - name: Checkout
        uses: actions/checkout@v3
        with:
          #fetch-depth を指定しないと、
          #push 直前のコミットが取得できない
          fetch-depth: 1
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu' # See 'Supported distributions' for available options
          java-version: '11'
          cache: 'gradle'
      - name: Build Gradle
        uses: gradle/gradle-build-action@v2
      - name: AVD cache
        uses: actions/cache@v3
        id: avd-cache
        with:
          path: |
            ~/.android/avd/*
            ~/.android/adb*
          key: avd-${{ matrix.api-level }}-${{ matrix.target }}-${{ matrix.arch }}

      - name: Create AVD and Generate Snapshot for Caching
        if: steps.avd-cache.outputs.cache-hit != 'true'
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          target: ${{ matrix.target }}
          arch: ${{ matrix.arch }}
          force-avd-creation: false
          emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: false
          script: echo "Generated AVD snapshot for caching."
      - name: Flutter Setup
        uses: ./.github/actions/build
      - name: Run integration tests
        # more info on https://github.com/ReactiveCircus/android-emulator-runner
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          arch: x86_64
          profile: Nexus 6
          script: flutter test integration_test
    