name: Flutter_Test

#on: [] で、[]が実行された際に
on:
  pull_request:
    types: [opened, synchronize]

env:
  API_KEY: ${{secrets.API_KEY}}

jobs:
  flutter_test:
    #最新バージョンのubuntu環境を準備する
    runs-on: macos-13
    timeout-minutes: 10
    steps:
    
      #ソースコードを取得
      - uses: actions/checkout@v3
        with:
          #fetch-depth を指定しないと、
          #push 直前のコミットが取得できない
          fetch-depth: 1
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true
      - run: flutter pub get
      - run: flutter gen-l10n
      - run: flutter pub run build_runner build --delete-conflicting-outputs
      - uses: vhanda/flutter-build-runner-action@v1
        with:
          output_paths: |
            lib/generated/
            lib/**/*.g.dart
      - run: flutter test