name: Flutter_Analyze

on:
  pull_request:
    types: [opened, synchronize]

env:
  API_KEY: ${{secrets.API_KEY}}

jobs:
  #静的解析
  flutter_analyze:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Flutter Setup
        uses: ./.github/actions/build
      #静的解析
      - name: Flutter Analyze
        run: flutter analyze
