name: Flutter_Test

#on: [] で、[]が実行された際に
on:
  pull_request:
    types: [opened, synchronize]

jobs:
  flutter_test:
    #最新バージョンのubuntu環境を準備する
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      #ソースコードを取得
      - uses: actions/checkout@v3
        with:
          #fetch-depth を指定しないと、
          #push 直前のコミットが取得できない
          fetch-depth: 1
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true
      - run: flutter pub get
      - run: flutter test