name: Flutter_Analyze

on:
  pull_request:
    types: [opened, synchronize]

env:
  API_KEY: ${{secrets.API_KEY}}

jobs:
  #静的解析
  flutter_analyze:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        #ソースコードを取得
        uses: actions/checkout@v3
        with:
          #fetch-depth を指定しないと、
          #push 直前のコミットが取得できない
          fetch-depth: 1
      #Flutter SDK の設定
      - name: Setup Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true
      #依存関係読み込み
      - name: Run Flutter Pub Get
        run: flutter pub get
      - run: flutter gen-l10n
      #コードの自動生成
      - name: Run Build Runner
        run: flutter pub run build_runner build --delete-conflicting-outputs
      # - uses: vhanda/flutter-build-runner-action@v1
      #静的解析
      - name: Flutter Analyze
        run: flutter analyze
